name: fluttersample
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+1
  fl_chart: ^0.51.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.1
  # sqLite プラグイン
  sqflite:
  # OSごとのディレクトリ管理
path:

flutter_native_splash:
  image: "images/icon.png"
  color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
